[project]
name = "fttb"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "asgiref>=3.8.1",
    "flask-sqlalchemy>=3.1.1",
    "uvicorn>=0.34.3",
]
